EcommercePerifericos/Controllers/BackUserController.cs
using EcommercePerifericos.Models.DB;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace EcommercePerifericos.Controllers
{
    [Authorize]
    public class BackUserController : Controller
    {
        private Models.DB.AleshopBdContext dbContext;
        public BackUserController(Models.DB.AleshopBdContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index()
        {
            var roles = dbContext.Rols.ToList();
            ViewBag.Roles = roles;
            return View();
        }

        public async Task<IActionResult> UserList()
        {
            List<Usuario>User = await dbContext.Usuarios
                .Include(u => u.IdRolNavigation)
                .ToListAsync();

            try
            {
                var userDTO = User.Select(u => new
                {
                    u.Id,
                    u.Nombre,
                    u.Apellido,
                    u.Email,
                    u.Contrasenia,
                    u.IdRol,
                    Rol = u.IdRolNavigation?.Tipo ?? "Sin Rol"
                });

                return Json(new { data = userDTO });
            }
            catch (Exception ex)
            {
                Debug.WriteLine($"Error al cargar usuarios: {ex.Message}");
                return Json(new { data = new List<object>() });
            }
            
        }

        [HttpPost]
        public IActionResult CrearUsuario(Usuario nuevoUsuario)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    // Realizar lógica de creación de producto, por ejemplo, guardar en la base de datos
                    dbContext.Usuarios.Add(nuevoUsuario);
                    dbContext.SaveChanges();

                    // Opcional: Redirigir a una página de éxito o mostrar un mensaje de éxito en la vista
                    TempData["SuccessMessage"] = "Usuario creado exitosamente.";

                    // Redirigir a una página de éxito o regresar a la vista original
                    return RedirectToAction("Index");
                }
                else
                {
                    TempData["ErrorMessage"] = "Datos de usuario no válidos.";
                    return RedirectToAction("Index");
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error al Crear Usuario: {ex.Message}");

                TempData["ErrorMessage"] = "Ha ocurrido un error al crear usuario.";
                return RedirectToAction("Index");
            }
            
        }

        [HttpPost]
        public IActionResult EliminarUsuario(int id)
        {
            try
            {
                var usuarioExistente = dbContext.Usuarios.Find(id);
                if (usuarioExistente != null)
                {
                    dbContext.Usuarios.Remove(usuarioExistente);
                    dbContext.SaveChanges();
                    TempData["SuccessMessage"] = "Usuario eliminado exitosamente.";
                    return Json(new { success = true });
                }
                else
                {
                    TempData["ErrorMessage"] = "El usuario no existe.";
                    return Json(new { success = false });
                }
            }
            catch (DbUpdateException ex)
            {
                var innerException = ex.InnerException;
                string? errorMessage = innerException?.Message;


                Console.WriteLine(errorMessage);

                TempData["ErrorMessage"] = "Ha ocurrido un error al eliminar el usuario.";
                return Json(new { success = false });
            }
        }

        [HttpPost]
        public IActionResult ModificarUsuario(Usuario usuarioModificado)
        {
            try
            {
                if (usuarioModificado != null)
                {
                    var usuarioExistente = dbContext.Usuarios.Find(usuarioModificado.Id);
                    if (usuarioExistente != null)
                    {
                        // Actualizar las propiedades del producto existente con los valores modificados
                        usuarioExistente.Nombre = usuarioModificado.Nombre;
                        usuarioExistente.Apellido = usuarioModificado.Apellido;
                        usuarioExistente.Email = usuarioModificado.Email;
                        usuarioExistente.IdRol = usuarioModificado.IdRol;
                        usuarioExistente.Contrasenia = usuarioModificado.Contrasenia;

                        Console.WriteLine("Usuario Modificado:");
                        Console.WriteLine(usuarioModificado);

                        // Guardar los cambios en la base de datos
                        dbContext.SaveChanges();

                        TempData["SuccessMessage"] = "Usuario modificado exitosamente.";
                    }
                    else
                    {
                        TempData["ErrorMessage"] = "El usuario no existe.";
                    }

                    return RedirectToAction("Index");
                }

                return View("Index", usuarioModificado);

            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error en ModificarProducto: {ex.Message}");

                TempData["ErrorMessage"] = "Ha ocurrido un error al modificar el producto.";
                return RedirectToAction("Index");
            }
        }
    }
}

EcommercePerifericos/Controllers/ProductController.cs
using EcommercePerifericos.Models;
using EcommercePerifericos.Models.DB;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;

namespace EcommercePerifericos.Controllers
{
    public class ProductController : Controller
    {
        private Models.DB.AleshopBdContext dbContext;
        public ProductController(Models.DB.AleshopBdContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult ProductDetail()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ProductList(int categoriaID)
        {
            List<Producto> productos;

            try
            {
                if(categoriaID > 0)
                {
                    productos = await dbContext.Productos.Where(p => p.IdCategoria == categoriaID && p.Activo == "activo").ToListAsync();
                }
                else
                {
                    productos = await dbContext.Productos
                    .Include(p => p.IdCategoriaNavigation)
                    .Where(p => p.Activo == "activo")
                    .ToListAsync();
                }
                
                var productosDTO = productos.Select(p => new
                {
                    p.Id,
                    p.Img,
                    p.Nombre,
                    p.Stock,
                    categoria = p.IdCategoriaNavigation?.Nombre,
                    p.IdCategoria,
                    p.Precio,
                    p.Activo,
                    p.Detalle,
                    p.PrecioOferta
                });

                return Json(new { data = productosDTO });

            }
            catch (Exception ex)
            {
                return Json(new { error = ex.Message, data = new List<object>() });
            }
        }

        [HttpGet]
        public async Task<IActionResult> CategoriesList()
        {
            List<Categorium> categorias = await dbContext.Categoria.ToListAsync();

            try
            {
                var categoriasDTO = categorias.Select(c => new
                {

                    c.Id,
                    c.Nombre

                });

                return Json(new { data = categoriasDTO });

            }
            catch(Exception ex)
            {
                return Json(new { data = new List<object>() });
            }
        }

        [HttpPost]
        public async Task<IActionResult> ProductDetailProduct([FromBody] int productoID)
        {
            var producto = await dbContext.Productos
                .Include(p => p.IdCategoriaNavigation)
                .Where(p => p.Id == productoID)
                .FirstOrDefaultAsync();

            if (producto == null)
            {
                // Manejar el caso en que no se encuentre el producto
                return Json(new { success = false, message = "Producto no encontrado" });
            }

            // Mapear el producto a un objeto anónimo con los datos necesarios
            var model = new ProductoViewModel
            (
                producto.Id,
                producto.Img,
                producto.Nombre,
                producto.Stock,
                producto.IdCategoriaNavigation?.Nombre,
                producto.IdCategoria,
                producto.Precio,
                producto.Activo,
                producto.Detalle,
                producto.PrecioOferta
            );

            // Devolver un JSON indicando el éxito y, opcionalmente, los datos del producto
            return Json(new { success = true, data = model });
        }


    }
}

EcommercePerifericos/Controllers/SessionController.cs
using EcommercePerifericos.Models.DB;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;
using Microsoft.AspNetCore.Authorization;

namespace EcommercePerifericos.Controllers
{
    public class SessionController : Controller
    {
        private Models.DB.AleshopBdContext dbContext;
        public SessionController(Models.DB.AleshopBdContext dbContext)
        {
            this.dbContext = dbContext;
        }
        public IActionResult Index()
        {
            ClaimsPrincipal claimUser = HttpContext.User;
            if (claimUser.Identity.IsAuthenticated)
            {
                return RedirectToAction("Index", "Home");
            }

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(Usuario model)
        {
            if (ModelState.IsValid)
            {              
                    var user = dbContext.Usuarios.SingleOrDefault(u => u.Email == model.Email);

                    if (user != null && user.Contrasenia == model.Contrasenia)
                    {
                        List<Claim> claims = new List<Claim>()
                        {
                            new Claim(ClaimTypes.Name, model.Email)
                        };

                        ClaimsIdentity claimsIdentity = new ClaimsIdentity(claims,
                            CookieAuthenticationDefaults.AuthenticationScheme);

                        AuthenticationProperties properties = new AuthenticationProperties()
                        {
                            AllowRefresh = true,
                            IsPersistent = false
                        };

                        await HttpContext.SignInAsync(CookieAuthenticationDefaults.AuthenticationScheme,
                            new ClaimsPrincipal(claimsIdentity), properties);

                        return RedirectToAction("Index", "Home");
                    }
                    else
                    {
                        ModelState.AddModelError(string.Empty, "Credenciales inválidas. Por favor, inténtelo de nuevo.");
                    }
            }
            ViewData["ValidateMEssage"] = "user not found";
            return View();
        }

        public async Task<IActionResult> Logout()
        {
            await HttpContext.SignOutAsync(CookieAuthenticationDefaults.AuthenticationScheme);
            return RedirectToAction("Index", "Home");
        }
    }
}

EcommercePerifericos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcommercePerifericos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/EcommercePerifericos.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.2/font/bootstrap-icons.min.css">
</head>
<body>
    <header>
        <div class="bg-light d-flex justify-content-center">
            <p class="textHeader mb-0"><b>Merry Christmas 40% OFF</b></p>
        </div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Navbar</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Product" asp-action="Index">PRODUCTOS</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#">FAQ</a>
                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                CATEGORIAS
                            </a>
                            <ul class="dropdown-menu bg-dark" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item text-white" href="#">Mouse</a></li>
                                <li><a class="dropdown-item text-white" href="#">Teclado</a></li>
                                <li><a class="dropdown-item text-white" href="#">Monitor</a></li>
                            </ul>
                        </li>
                    </ul>

                    <form class="d-flex me-lg-4 mt-md-2 mb-md-2">
                        <div class="input-group">
                            <input class="form-control input-box" type="search" placeholder="Search" aria-label="Search">
                            <i class="bi bi-search icon-search" style="color: black;"></i>
                        </div>
                    </form>
                    <ul class="navbar-nav flex-row">
                        <a asp-area="" asp-controller="Favorite" asp-action="Index">
                            <li class="nav-link nav-link-right"><i class="bi bi-suit-heart-fill"></i></li>
                        </a>
                        <a asp-area="" asp-controller="Favorite" asp-action="Index">
                            <li class="nav-link nav-link-right"><i class="bi bi-bag-fill"></i></li>
                        </a>                       
                        @if (User.Identity.IsAuthenticated){
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                    <i class="bi bi-people-fill nav-link-right-final"></i>
                                </a>
                                <ul class="dropdown-menu dropdown-menu-end bg-dark" aria-labelledby="navbarDropdownMenuLink">
                                    <li><a class="dropdown-item text-white" asp-area="" asp-controller="BackProduct" asp-action="Index">PRODUCTOS</a></li>
                                    <li><a class="dropdown-item text-white" asp-area="" asp-controller="BackUser" asp-action="Index">USUARIOS</a></li>
                                    <li><a class="dropdown-item text-white" asp-area="" asp-controller="Session" asp-action="Logout">CERRAR SESION</a></li>
                                </ul>
                            </li>
                            }                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container-fluid">
        @RenderBody()      
    </div>

    <footer class="text-white text-center text-lg-start bg-dark">
            <div class="container p-4">
                <div class="row mt-4">
                    <div class="col-lg-4 col-md-12 mb-4 mb-md-0">
                        <h5 class="text-uppercase mb-4">About company</h5>
                        <p>
                            At vero eos et accusamus et iusto odio dignissimos ducimus qui blanditiis praesentium
                            voluptatum deleniti atque corrupti.
                        </p>
                        <p>
                            Blanditiis praesentium voluptatum deleniti atque corrupti quos dolores et quas
                            molestias.
                        </p>
                        <div class="mt-4">
                        <a type="button" href="#" class="btn btn-floating btn-icon-footer btn-lg"><i class="bi bi-facebook icon-footer"></i></a>
                        <a type="button" href="#" class="btn btn-floating btn-icon-footer btn-lg"><i class="bi bi-instagram icon-footer"></i></a>
                        <a type="button" href="#" class="btn btn-floating btn-icon-footer btn-lg"><i class="bi bi-twitter icon-footer"></i></a>
                        <a type="button" href="#" class="btn btn-floating btn-icon-footer btn-lg"><i class="bi bi-whatsapp icon-footer"></i></a>
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase mb-4 pb-1 footer-contact">Contact</h5>
                    <ul class="fa-ul list-unstyled">
                            <li class="mb-3">
                                <span class="fa-li"><i class="fas fa-home"></i></span><span class="ms-2">New York, NY 10012, US</span>
                            </li>
                            <li class="mb-3">
                                <span class="fa-li"><i class="fas fa-envelope"></i></span><span class="ms-2">info@example.com</span>
                            </li>
                            <li class="mb-3">
                                <span class="fa-li"><i class="fas fa-phone"></i></span><span class="ms-2">+ 01 234 567 88</span>
                            </li>
                            <li class="mb-3">
                                <span class="fa-li"><i class="fas fa-print"></i></span><span class="ms-2">+ 01 234 567 89</span>
                            </li>
                        </ul>
                    </div>
                    <div class="col-lg-4 col-md-6 mb-4 mb-md-0">
                        <h5 class="text-uppercase mb-4">Opening hours</h5>

                        <table class="table text-center text-white">
                            <tbody class="font-weight-normal">
                                <tr>
                                    <td>Mon - Thu:</td>
                                    <td>8am - 9pm</td>
                                </tr>
                                <tr>
                                    <td>Fri - Sat:</td>
                                    <td>8am - 1am</td>
                                </tr>
                                <tr>
                                    <td>Sunday:</td>
                                    <td>9am - 10pm</td>
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            <div class="text-center p-1 footer-copy">
                © 2023 Copyright:
                <p class="text-white mb-0">EcommerceShop</p>
            </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>